name: Tests Mend Scan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment selection'
        required: true
        default: 'dev-com'
        type: choice
        options: 
          - dev-com
          - stage-com
      currentVmName:
        description: 'VM Name to run Mend Scan'
        required: true
        default: 'VM-DEV'
        type: string
      userkey:
        description: 'User Key'
        required: true
        type: string
jobs:
 build:
   runs-on: ubuntu-latest
   env:
     RESOURCE_GROUP: "group-1"
     VM_NAME: ${{ github.event.inputs.currentVmName }}
     MEND_APIKEY: ${{ secrets.MEND_API_KEY }}
     MEND_USERKEY: ${{ github.event.inputs.userkey }}
   
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Print variables for debugging
       run: |
         echo "VM_NAME is $VM_NAME"
         echo "MEND_APIKEY is $MEND_APIKEY"
         echo "MEND_USERKEY is $MEND_USERKEY"
         echo "RESOURCE_GROUP is $RESOURCE_GROUP"
   
     - name: Setting Mend environment variables
       run: |
         az vm run-command invoke --command-id RunShellScript --name ${{ env.VM_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --scripts '
           export WS_APIKEY=${{ secrets.MEND_API_KEY }}
           export WS_USERKEY=${{ env.MEND_USERKEY }}
           export WS_PRODUCTNAME="prodname"
           export WS_PROJECTNAME="projectname"
           export WS_WSS_URL="https://t"
         '
